### ISSUE TITLE
Why not use your own DragonFly box that you made in another repo here?

### ISSUE THREAD

**Issue by strangelittlemonkey** [mcandre/vagrant-dragonfly-rust#2]
https://github.com/mcandre/vagrant-dragonfly-rust/blob/7bb4ca027ee93eb6f5ba5594248eddddbc0164bb/Vagrantfile#L2

**Comment by mcandre** [comment]
In the interest of time, I started with a known half-decent base box, b00ga/dragonfly50. Once I realized that many operating systems have broken base boxes on Vagrant Cloud, or even no base box on Vagrant Cloud, then I went back and packed some base boxes. There's a lot of work going into mcandre/packer-templates, and I'm still fixing some things there.

There is also something to be said for me not having to personally maintain a base box, reinvent the wheel, fix all the things. Though in this case I will make an exception, as b00ga/dragonfly50 doesn't enable Vagrant synced folders by default, which I think is an oversight in any Vagrant box worth using.

The big project I'm working on right now is mcandre/tonixxx, a Vagrant wrapper to automate porting systems language applications for many different operating system kernels at once. I'm primarily working on getting the "fewer" buildbot Vagrant boxes working for the tonixxx demo, though in order to support that work I am going back to some of my vagrant-*-cpp and vagrant-*-rust boxes from time to time to patch them up. As I write this, I'm rebuilding several Vagrant boxes, including this one. Then I'll republish these to Vagrant Cloud :)
